/**
 * Build an `AdminResourceSpec` from a discovered repository and its
 * table meta. Pure function. The autogen validators are passed in so
 * this module does not cross the `schema/` package boundary during the
 * parallel build phase.
 */
import type { TObject } from '@sinclair/typebox';

import type {
  AdminResourceSpec,
  ColumnMeta,
  DiscoveredRepository,
  FieldSpec,
  ListViewSpec,
  RelationDescriptor,
  TableMeta,
} from '../types.js';

import { inferWidget } from './infer-widget.js';

/**
 * Local structural type for the autogenerated TypeBox validators. Mirrors
 * `src/schema/autogen-validators.ts` (written by agent A) without taking
 * a hard import dependency on that file -- the boundary between the
 * discovery and schema sub-phases is intentionally enforced at build time.
 */
export interface AutogenValidators {
  readonly create: TObject;
  readonly update: TObject;
}

export interface InferSpecOptions {
  readonly discovered: DiscoveredRepository;
  readonly tableMeta: TableMeta;
  readonly validators: AutogenValidators;
}

const MAX_LIST_COLUMNS = 6;

const humanise = (raw: string): string => {
  if (raw.length === 0) return raw;
  const words = raw
    .replaceAll(/[_-]+/g, ' ')
    .replaceAll(/([a-z0-9])([A-Z])/g, '$1 $2')
    .trim()
    .split(/\s+/);
  return words
    .map((w) =>
      w.length === 0 ? w : w[0]!.toUpperCase() + w.slice(1).toLowerCase(),
    )
    .join(' ');
};

const singularise = (word: string): string => {
  if (word.endsWith('ies')) return word.slice(0, -3) + 'y';
  if (word.endsWith('ses')) return word.slice(0, -2);
  if (word.endsWith('es') && word.length > 3) return word.slice(0, -2);
  if (word.endsWith('s') && !word.endsWith('ss')) return word.slice(0, -1);
  return word;
};

const toSubject = (table: string): string => {
  const parts = table.split(/[_-]+/).filter((p) => p.length > 0);
  if (parts.length === 0) return table;
  const pascal = parts
    .map((p) => p[0]!.toUpperCase() + p.slice(1).toLowerCase())
    .join('');
  return singularise(pascal);
};

const toFieldSpec = (column: ColumnMeta): FieldSpec => ({
  name: column.name,
  label: humanise(column.name),
  widget: inferWidget(column),
  required:
    !column.nullable && column.defaultValue === null && !column.generated,
  readOnly: column.generated || column.isPrimaryKey,
  nullable: column.nullable,
  maxLength: column.maxLength,
  enumValues: column.enumValues,
  references: column.references,
  placeholder: null,
  help: null,
});

const buildListColumns = (
  columns: readonly ColumnMeta[],
): readonly string[] => {
  const pk = columns.find((c) => c.isPrimaryKey);
  const rest = columns.filter(
    (c) => !c.generated && c.name !== 'deletedAt' && !c.isPrimaryKey,
  );
  const ordered: string[] = [];
  if (pk) ordered.push(pk.name);
  for (const c of rest) ordered.push(c.name);
  return ordered.slice(0, MAX_LIST_COLUMNS);
};

const buildSearch = (columns: readonly ColumnMeta[]): readonly string[] =>
  columns
    .filter(
      (c) =>
        (c.type === 'text' || c.type === 'varchar') &&
        !c.generated &&
        !c.isPrimaryKey &&
        c.references === null,
    )
    .map((c) => c.name);

const buildDefaultSort = (
  tableMeta: TableMeta,
): ListViewSpec['defaultSort'] => {
  const hasCreatedAt = tableMeta.columns.some((c) => c.name === 'createdAt');
  if (hasCreatedAt) return { field: 'createdAt', order: 'desc' };
  const pk = tableMeta.primaryKey[0] ?? tableMeta.name;
  return { field: pk, order: 'desc' };
};

const buildSortable = (tableMeta: TableMeta): readonly string[] => {
  const out: string[] = [];
  const seen = new Set<string>();
  const push = (name: string): void => {
    if (seen.has(name)) return;
    seen.add(name);
    out.push(name);
  };

  for (const c of tableMeta.columns) {
    if (c.references !== null) continue;
    if (c.generated && !c.isPrimaryKey) continue;
    push(c.name);
  }
  for (const c of tableMeta.columns) {
    if (c.name === 'createdAt' || c.name === 'updatedAt') push(c.name);
  }
  for (const pk of tableMeta.primaryKey) push(pk);

  return out;
};

const buildRelations = (
  fields: readonly FieldSpec[],
): Readonly<Record<string, RelationDescriptor>> => {
  const relations: Record<string, RelationDescriptor> = {};
  for (const f of fields) {
    if (f.references !== null) {
      relations[f.name] = { resource: f.references.table, display: 'id' };
    }
  }
  return relations;
};

export const inferSpec = (opts: InferSpecOptions): AdminResourceSpec => {
  const { discovered, tableMeta, validators } = opts;
  const fields = tableMeta.columns.map((c) => toFieldSpec(c));

  const list: ListViewSpec = {
    columns: buildListColumns(tableMeta.columns),
    search: buildSearch(tableMeta.columns),
    defaultSort: buildDefaultSort(tableMeta),
    sortableFields: buildSortable(tableMeta),
  };

  return {
    name: tableMeta.name,
    table: tableMeta.name,
    repositoryKey: discovered.repositoryKey,
    label: humanise(tableMeta.name),
    icon: null,
    fields,
    list,
    form: { fieldsets: null },
    relations: buildRelations(fields),
    rowActions: [],
    permissions: { subject: toSubject(tableMeta.name) },
    hasSoftDelete: tableMeta.hasSoftDelete,
    tenantScoped: tableMeta.hasTenantColumn,
    scope: tableMeta.hasTenantColumn ? 'tenant' : 'system',
    group: null,
    detailActions: [],
    validators: { create: validators.create, update: validators.update },
  };
};
