import type { ModuleNames } from '../util/names.ts';

export interface InferredColumn {
  readonly name: string;
  readonly dataType: string;
  readonly isNullable: boolean;
  readonly defaultValue: string | null;
  readonly udtName: string;
}

export interface AdminTemplateInput {
  readonly names: ModuleNames;
  readonly columns: readonly InferredColumn[];
  readonly subject: string;
}

const AUDIT_COLUMNS = new Set(['id', 'createdAt', 'updatedAt', 'deletedAt']);

const SENSITIVE_COLUMN_PATTERNS = [
  /password/i,
  /secret/i,
  /token/i,
  /hash/i,
  /api_?key/i,
];

const TEXT_COLUMN_PATTERNS = [/content/i, /body/i, /description/i, /notes?/i];

const isSensitive = (column: string): boolean =>
  SENSITIVE_COLUMN_PATTERNS.some((re) => re.test(column));

const isLongText = (col: InferredColumn): boolean =>
  col.dataType === 'text' ||
  TEXT_COLUMN_PATTERNS.some((re) => re.test(col.name));

const formatStringArray = (values: readonly string[]): string => {
  if (values.length === 0) return '[]';
  return `[${values.map((v) => `'${v}'`).join(', ')}]`;
};

/**
 * Emits a `*.admin.ts` file pre-filled with sensible defaults inferred from
 * the live `information_schema`. The generated file mirrors the style of
 * hand-written admin overrides in `users.admin.ts` / `posts.admin.ts`.
 */
export const adminTemplate = ({
  names,
  columns,
  subject,
}: AdminTemplateInput): string => {
  const hidden = columns
    .filter((c) => isSensitive(c.name) || c.name === 'deletedAt')
    .map((c) => c.name);

  const readOnly = columns
    .filter((c) => AUDIT_COLUMNS.has(c.name) && c.name !== 'deletedAt')
    .map((c) => c.name);

  const widgets = columns
    .filter((c) => isLongText(c))
    .map((c) => `    ${c.name}: 'textarea',`);

  const listColumns = columns
    .filter(
      (c) => !hidden.includes(c.name) && c.name !== 'id' && !isLongText(c),
    )
    .map((c) => c.name)
    .slice(0, 6);
  if (
    !listColumns.includes('createdAt') &&
    columns.some((c) => c.name === 'createdAt')
  ) {
    listColumns.push('createdAt');
  }

  const searchableColumns = columns
    .filter(
      (c) =>
        (c.dataType === 'text' ||
          c.dataType.includes('character varying') ||
          c.dataType === 'varchar') &&
        !hidden.includes(c.name),
    )
    .map((c) => c.name)
    .slice(0, 3);

  const sortableFields = columns
    .filter(
      (c) => !hidden.includes(c.name) && c.name !== 'id' && !isLongText(c),
    )
    .map((c) => c.name);

  const hiddenOut = formatStringArray(hidden);
  const readOnlyOut = formatStringArray(readOnly);
  const listColumnsOut = formatStringArray(listColumns);
  const searchOut = formatStringArray(searchableColumns);
  const sortableOut = formatStringArray(sortableFields);

  return `import { defineAdminResource } from '@kit/admin';

/**
 * Admin panel override for the \`${names.plural.camel}\` resource.
 * Generated by \`pnpm generate admin ${names.plural.kebab}\` -- tweak freely.
 */
export default defineAdminResource('${names.plural.camel}', async () => ({
  label: '${names.plural.title}',
  hidden: ${hiddenOut},
  readOnly: ${readOnlyOut},
  widgets: {
${widgets.join('\n')}
  },
  list: {
    columns: ${listColumnsOut},
    search: ${searchOut},
    defaultSort: { field: 'createdAt', order: 'desc' },
    sortableFields: ${sortableOut},
  },
  permissions: { subject: '${subject}' },
}));
`;
};
